[WIP] Ticket esp http
botsgeek/smart_weather_station pull request #18
Opened 2024-05-02 10:26 UTC by Rsaliu

Add esp-http class to enable http communication to STM32 via ESP32. Supported functions for now.

  Basic http and https REST calls (GET, POST, PUT, DELETE, HEAD).

  Special large post request is also supported

  An issue noticed for now is that there is no way to get http error code,
  this issue as been logged on the esp-at repo, awaiting response.

Outstanding item is to add example and cleanup

2024-05-02 12:19 UTC, Jayozone1 reviewed
I went through the changes made, I can saw the review made is okay by me

2024-05-02 14:05 UTC, Dave-Olo approved these changes

2024-05-03 20:24 UTC, Dave-Olo requested changes
Kindly remove the main.c changes

2024-05-03 20:48 UTC, Rsaliu commented
> Kindly remove the main.c changes

Thanks @Dave-Olo .

main.c changes removed

2024-05-04 15:19 UTC, Dave-Olo approved these changes

2024-06-04 14:41 UTC, merged